on:
  workflow_dispatch:
    inputs:
      environment:
          description: 'Environment to deploy'
          type: environment
          required: true
jobs:
 deployment:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: deploy
        run: true
